version: '3.8'
services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"



  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: mysecret
    ports:
      - "5432:5432"



  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"


